# This file was generated by GoReleaser. DO NOT EDIT.
cask "nh-cli" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "86912ab29dd46925e856c19917483d56d2789b63d21ea9e71e85c0f52855cce5"
      url "https://github.com/nerves-hub/nh/releases/download/v#{version}/nh_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a28afe158d4ac598948b001fad5f6775b070f845528a947186fc7fa26611ac36"
      url "https://github.com/nerves-hub/nh/releases/download/v#{version}/nh_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3287b672ce64f759b1543e470b25f1b77828e8e56d7baea88e9f9253a294cda9"
      url "https://github.com/nerves-hub/nh/releases/download/v#{version}/nh_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5ec312d7c41a7cdb15cb91c943fa3cb42112a6036823d8c3f2d29e49256e8696"
      url "https://github.com/nerves-hub/nh/releases/download/v#{version}/nh_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nh-cli"
  desc "Command-line interface for NervesCloud / NervesHub"
  homepage "https://github.com/nerves-hub/nh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nh"

  postflight do
    if OS.mac? && File.executable?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nh"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This cask installs the `nh` command. The old Elixir CLI installs an `nh`
    formula that provides the same command. If you have it, remove it first:
      brew uninstall nerves-hub/tap/nh
  EOS
end
