# This file was generated by GoReleaser. DO NOT EDIT.
cask "nh-cli" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "ec56e13eb27db25b92f45862253126b7ef648ed123a5fb8594de475da32888e0"
      url "https://github.com/nerves-hub/nh/releases/download/v#{version}/nh_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c06bfce0ad9d7ee25a72cfd3017119f01a9e8d56607884b3a02abdad30deb04d"
      url "https://github.com/nerves-hub/nh/releases/download/v#{version}/nh_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0f2c8c3bd4f555244afd0efb84cb5903fb0f91fab923f0b668c099c8954b5dc8"
      url "https://github.com/nerves-hub/nh/releases/download/v#{version}/nh_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5acec0f1fc1e604cbd2cbe14620f59b1e8d401a3d8042951bd76ad70d3793acc"
      url "https://github.com/nerves-hub/nh/releases/download/v#{version}/nh_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nh-cli"
  desc "Command-line interface for NervesCloud / NervesHub"
  homepage "https://github.com/nerves-hub/nh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nh"

  postflight do
    if OS.mac? && File.executable?("/usr/bin/xattr")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nh"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This cask installs the `nh` command. The old Elixir CLI installs an `nh`
    formula that provides the same command. If you have it, remove it first:
      brew uninstall nerves-hub/tap/nh
  EOS
end
