# This file was generated by GoReleaser. DO NOT EDIT.
cask "nh-cli" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "98f11d41d9899ea2562c32375a38b61d1e81e36fc5082953895912e2698d7e30"
      url "https://github.com/nerves-hub/nh/releases/download/v#{version}/nh_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ba2fa7747a0b4ebc2c5810bf4f48fb29d7dd204d1f09df3222975c21c0831a0b"
      url "https://github.com/nerves-hub/nh/releases/download/v#{version}/nh_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e334b7227c05bb7ebffdcdfa52c9d54a32423a6069e3fd576ad6178e9695d2f3"
      url "https://github.com/nerves-hub/nh/releases/download/v#{version}/nh_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cb1ffa16652c8bf5c9ac84bae3ab186e3725a507f517fa564e6aebfb3ff6cf4e"
      url "https://github.com/nerves-hub/nh/releases/download/v#{version}/nh_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nh-cli"
  desc "Command-line interface for NervesCloud / NervesHub"
  homepage "https://github.com/nerves-hub/nh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nh"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This cask installs the `nh` command. The old Elixir CLI installs an `nh`
    formula that provides the same command. If you have it, remove it first:
      brew uninstall nerves-hub/tap/nh
  EOS
end
